<?php

namespace AppBundle\Repository;

/**
 * CategoryLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
