<?php

namespace AppBundle\Repository;

/**
 * DishLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
