<?php

namespace AppBundle\Repository;

/**
 * DishPortionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishPortionRepository extends \Doctrine\ORM\EntityRepository
{
}
