<?php

namespace AppBundle\Repository;

/**
 * DishIconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishIconRepository extends \Doctrine\ORM\EntityRepository
{
}
