<?php

namespace AppBundle\Repository;

/**
 * FirstUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirstUserRepository extends \Doctrine\ORM\EntityRepository
{
}
