<?php

namespace AppBundle\Repository;

/**
 * OrdenDishPortionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenDishPortionRepository extends \Doctrine\ORM\EntityRepository
{
}
