<?php

namespace AppBundle\Repository;

/**
 * OrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenRepository extends \Doctrine\ORM\EntityRepository {

    public function findAll() {
        return $this->findBy(array(), array('dateOrder' => 'DESC'));
    }
    
    public function findByStatus() {
        return $this->findBy(array('status' => 'En cours'), array('dateOrder' => 'DESC'));
    }

}
