<?php

namespace AppBundle\Repository;

/**
 * PortionLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortionLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
